### ISSUE TITLE
use t.Helper() in storage testsuit

### ISSUE THREAD

**Issue by kopiczko** [giantswarm/microstorage#21]
Details about the function here: https://blog.golang.org/go1.9

**Comment by kopiczko** [comment]
@fgimenez pointed that this https://golang.org/pkg/testing/#hdr-Subtests_and_Sub_benchmarks is also useful.

We could create a struct containing storage and run all those https://github.com/giantswarm/microstorage/blob/master/storagetest/storagetest.go#L19-L24 as methods of that struct.

**Comment by xh3b4sd** [comment]
I would say just do it or lets get rid of this issue. I want to clean the board.
